-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 02:10:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clientesmenor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clientesmenor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clientesmenor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clientesmenor` ;

-- -----------------------------------------------------
-- Table `clientesmenor`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientesmenor`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clientesmenor`.`operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientesmenor`.`operaciones` (
  `idOperaciones` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  PRIMARY KEY (`idOperaciones`, `clientes_idclientes`),
  INDEX `fk_operaciones_clientes_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_operaciones_clientes`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `clientesmenor`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
